#!/usr/bin/env bash

echo '--- BEGIN CHECK ---'
checkupdates
pacaur -k
echo '--- WRAPPED UP ---'

read -p "Update all (y/n)?" choice
case "$choice" in 
  y|Y ) pacaur -Syu --noconfirm;;
  n|N ) echo "aborted";;
  * ) echo "invalid";;
esac
