#!/usr/bin/env bash

# store the total and free memory in two variables
#loads=mpstat -P ALL 1 1 | awk '/Average:/ && $2 ~ /[0-9]/ {print $3}'
#echo " ${loads[0]}%|${loads[1]}%|${loads[2]}%|${loads[3]}%"


echo " $[100-$(vmstat 1 2|tail -1|awk '{print $15}')]%"