#!/usr/bin/env bash

read lo int1 int2 <<< `ip link | sed -n 's/^[0-9]: \(.*\):.*$/\1/p'`

if iwconfig $int1 >/dev/null 2>&1; then
    wifi=$int1
    eth0=$int2
else 
    wifi=$int2
    eth0=$int1
fi

ip link show $eth0 | grep 'state UP' >/dev/null && int=$eth0 || int=$wifi

echo ""

STR=$(iwconfig wlp3s0 | grep Signal | awk '{print $2}' | sed -ne 's/^[^0-9]*\([0-9]*\).*/\1/p')
TOTAL=70
if ([[ ! $STR =~ ^-?[0-9]+$ ]]) then
percent=0
else
percent=$(awk "BEGIN { pc=100*${STR}/${TOTAL}; i=int(pc); print (pc-i<0.5)?i:i+1 }")
fi
echo "$percent"
#%" 
