#!/usr/bin/env bash

IN=$(ifstat | grep -o -P 'wlp3s0(\s*\d*){8}')
arrIN=(${IN//;/ })
rawUP=$(bc <<< "scale=0; ${arrIN[7]} / 1024/ 5" )
rawDOWN=$(bc <<< "scale=0; ${arrIN[5]} / 1024 / 5" )

if [ -z "$rawUP" ]
then
rawUP="0"
fi
if [ -z "$rawDOWN" ]
 then
rawDOWN="0"
fi

download="$rawDOWN kb/s"
upload="$rawUP kb/s"

echo " $upload  $download"